language: python
python:
- '3.5'
- '3.6'
script: pytest
deploy:
  provider: pypi
  user:
    secure: mKhhHCzWm4dNBXsRsRwXVkkq2c4yoQDNMUE8DSKnHO63uEq1sIuKfClC6k40hqr5TL8vkdkDCStjkcuBbwl4h5LlFlv7L2MdiXO8yMxMNWNHIumAAZR5NGKXbJtpDCDehxO8l+M6eRzbhz/eWliixRY8fsRjOR02XkZ9goDES+cZmqSGwmc0aFkL5egEmKzOfay07wpJ/uvKAjAAlDT9Rhy6Lnd/dsLf8ND++GlKxeUbHf9ESiSZ5zNJ60JjZMDrPO3mMAh4530PKk3wPiHAty5ZbZsZFsO6JmN4E2cCRJQaGoQwX7QrTFtnM6eQDPnvl1XEQ/BtHPwhg+1Uxqh4VwcgjvsyD9U0b+QZmr7x5QfIAqEe0UgxbpUpeL0MpoiisgrfxfEwis/JnhOh3WoNu6VYqswbUYyws4LhG/GmoUk+dnWEjmnz7QTLygwrLfVmcpOX3JA+69qb0sr4/GQhZNL5s3waT21tgLD3btdwoM1rZOWAuOHA++9Dhvzn0TOMyAX/bVL9J9fupenIaWMZfkmoclRpJiRmjJlJSWvWvTiiDYAr+x9wMGBd8EicYSjo6yuU/ocSB8I4oSfAGGt5WJmqYv8nF4W8HM2RoUKhMkr4PbRUFm5PAwS/cur16arumvDyA87K2sc4dCPF/KLg3UliMGMAYQz1Sq2+4ECFguk=
  password:
    secure: mVAJaXFdaOnCJFhf1Cg8kRQmre9Z7mr0L/sqJJ2N4q9/gUa4atGlsnSBcVXczVwoVlUqMx2/Bb44SctpiKCsfw1OUjU92r3DoRc7uPS1AA2W3TsJ3F69cqP7ht0kuAUTFs9fVBN3A44y4nizlJPHWmNq5hRuxeshFSctGrEiQE6wqrmBjGOm0ZUiYzRYgit43zKYfwjZD2vP3Ehsa5phjMDB71wOPa7+HrZGJN5x2Kw7dm5/IneuvBjtTmBuD1qGFadoBxStbb+s10JqcEIXtMLufltZePNjY9kc+B3S0h5myaVBEG9ijfBuuwEoZfGwEFhsTRwGMhkS74F9LicGPFeUctW/UxDrilLYtrSWFCpqc1X8Gfc9tMcMrhNa+xDX5ozKcqp0LQwMxFK/9tu5bbw2zvuKDfIczeM7BT6rkzVzmY3I414fVuy6UNdIk2E2HcTKeWEBzcwIefg9GANphjAqIqumBXxiDoIzJdj4Y+/D1JJsyJHSTfS4/JjEeozQPiJrfRC/pBc4fm1fYqJuZNAkCKdH68cDQgwgIBn5qDKrrr2LeZlZoC8iavhlNq8wn1CozqQb1cAKGTq8Jch6Kkf2LYFQaqV89n/eCRzreCS92VVpnX+kAPtSNxzG0iwBdHpgYX1mrIi6RRKcy+OFOQ4UqxLmAHEb+UIZmDGfsbU=
  on:
    tags: true
    python: '3.5'
